### PR TITLE
feat(DS-322): add remove command for remove TVM project

### PR DESCRIPTION
**Pull request by Henrrypg**
## Description

This PR is to add a command to remove TVM projects.

Also solves https://github.com/eduNEXT/tvm/issues/48

## Jira

[DS-322](https://edunext.atlassian.net/browse/DS-322)

## How to test

1. Install TVM on this branch
2. Create TVM project: `tvm project init test v13.3.1`
3. (Optional) You can init the same project in other path and move or rename it to test the messages.
4. Run `tvm project remove v13.3.1@test` or `tvm project remove v13.3.1@test --prune` 
5. Your .tvm in project folder, and root in ~/.tvm/{version}@{name} should be deleted. (With --prune it should delete all project folder)

- [ ] Test functionality
- [ ] Review changes in files

### CODE REVIEW

**Comment by dcoa** [comment]
This works, I just suggest be more clear about the difference between use the flag or not (for me isn't total clear, I had to test to be clear), 
The command to create a new project should be updated in the host to test for this PR  `tvm project init test v13.3.1 `.

**Comment by Henrrypg** [comment]
Thank you @dcoa, i have been correcting the order of the arguments and adding more information about the functionality of this command, you can test it again? the idea is be the clearest as possible.

**Review by JuanDavidBuitrago — DISMISSED** [review]
Its working well!! I think the documentation is clear to begin to use this command.

**Review by dcoa — APPROVED** [review]

**Comment by MaferMazu** [comment]
I tried to remove a project env following the documentation, and I can't do it.
Following the --help instructions, I could, and the correct form to call this functionality is: `tvm project remove <version>@<project-name>`
I think updating the doc and the PR with that information is a good idea. If I am wrong, please let me know; maybe I did something wrong.

On the other hand, I think it's better if we change Remove a Project to Remove a Project Environment subtitle in the doc to be clearer about what you will remove if you call that command, because when you use the flag, is clear. If you don't want to change the subtitle, maybe you can add a short description specifying what will be removed if you don't use the flag.

**Comment by JuanDavidBuitrago** [comment]
> I tried to remove a project env following the documentation, and I can't do it. Following the --help instructions, I could, and the correct form to call this functionality, following --help, is: `tvm project remove <version>@<project-name>` I think updating the doc and the PR with that information is a good idea. If I am wrong, please let me know; maybe I did something wrong.
> 
> On the other hand, I think it's better if we change the Remove a Project to Remove a Project Environment subtitle in the doc to be more explicit about what you will remove if you call this command, because when you use the flag, it is clear. If you don't want to change the subtitle, maybe you can add a short description specifying what will be removed if you don't use the flag.

You're right @MaferMazu, the documentation has to be changed

**Comment by Henrrypg** [comment]
Thank you @MaferMazu, the PR comment and docs are updated

**Review by JuanDavidBuitrago — APPROVED** [review]

**Review by MaferMazu — APPROVED** [review]
Looks good ✨ Thanks for updating the doc.

**Pull request merged**
