### PR TITLE
feat: add tvm documentation DS-243

### PR DESCRIPTION
**Pull request by MaferMazu**
## Description

This PR adds TVM documentation. 

## How to test

[Read the documentation](https://edunext-docs-tvm--55.com.readthedocs.build/en/55/)

## Aditional information

This PR comes from https://github.com/eduNEXT/edunext-internal-documentation/pull/10
It depends on #54

### CODE REVIEW

**Comment by MaferMazu** [comment]
@wlvasquez @johanv26 Maybe this would be interesting for you 🤗

**Comment by johanv26** [comment]
@MaferMazu thanks Mafer 😊

**Review by dcoa — APPROVED** [review]

**Review by Henrrypg — APPROVED** [review]

**Review by JuanDavidBuitrago — DISMISSED** [review]

**Comment by wlvasquez** [comment]
@MaferMazu : Hello, very good work and I like how you are following the suggestions for structuring the information and providing hyperlinks to the external resources.

I have a few notes and grammar points to share. Otherwise, great job!

In the **Step by step** section. Each step should end with a period, as they are grammatically structured sentences.

Under TVM as Environment Manager and TVM as Tutor Manager, the wording seems unnatural in the **NOTE** section.

Perhaps: "You need to activate the project environment to proceed." Instead of, "You need to have active the project environment."

Under TVM as Tutor Manager: the second bullet in TOC is not linked to topic. (Uninstall a Tutor version)

Creating two development environments: step-by-step (falta punto al final de las steps.)

Gracias :)

**Review by dcoa — DISMISSED** [review]

**Comment by MaferMazu** [comment]
Ready @wlvasquez 
- I added periods.
- I linked Uninstall a Tutor version
- I correct all notes for clarity

I'm attentive if you have more feedback 🤗

**Review by wlvasquez — COMMENTED** [review]
Thanks Mafer. Looks good. One small thing, it seems there may be an extra space in the note section after activate` , and before the comma.

Not sure with the spacing of the words. thanks

**Review by wlvasquez — DISMISSED** [review]
review, approved

**Comment by MaferMazu** [comment]
Thanks, well, I'm going to squash the commits, and when I have another review, I will merge this PR.

**Review by wlvasquez — APPROVED** [review]
reviewed, approved

**Review by dcoa — APPROVED** [review]

**Pull request merged**
